### PR TITLE
Update some mods* and fix some manifests

### PR DESCRIPTION
**Pull request by thefirethirteen**
* - manifests might be outdated

### CODE REVIEW

**Review by NebelNidas — APPROVED** [review]
Looks good so far! 👍

**Review by thefirethirteen — COMMENTED** [review]
Looks good to me too!

**Review by TacoMonkey11 — APPROVED** [review]
Seems fine
Edit: Approved after merged...

**Comment by thefirethirteen** [comment]
Thanks anyway :)

**Pull request merged**
