### PR TITLE
v4 migration

### PR DESCRIPTION
**Pull request by thefirethirteen**
Migrate the manifests to v4.
Update the manifests. (2021-11-16)
Add new manifest. (2021-11-16)
Add new manifest. (2021-11-16 to 2021-11-17)

### CODE REVIEW

**Review by NebelNidas — CHANGES_REQUESTED** [review]
Please keep all the `x`'s in the version filenames lower-case!

**Review by thefirethirteen — COMMENTED** [review]
Everything looks good!

**Review by thefirethirteen — COMMENTED** [review]
Looks good!

**Comment by NebelNidas** [comment]
Thank you two for this tremendous amount of work! 👍

**Pull request merged**
