### PR TITLE
Add manifest for `Giselbaer.advancementinfo`

### PR DESCRIPTION
**Pull request by thefirethirteen**

### CODE REVIEW

**Comment by TacoMonkey11** [comment]
there is no 1.3.1 version for this mod, or I can't find it

**Comment by TacoMonkey11** [comment]
I would recommend joining the 1.17 and 1.18 versions together in one file, just copy pasting it at the bottom

**Comment by thefirethirteen** [comment]
> there is no 1.3.1 version for this mod, or I can't find it

Follow the link under the version file?

**Comment by thefirethirteen** [comment]
> I would recommend joining the 1.17 and 1.18 versions together in one file, just copy pasting it at the bottom

Wdym they already are ;)

**Comment by TacoMonkey11** [comment]
> > there is no 1.3.1 version for this mod, or I can't find it
> 
> Follow the link under the version file?

yep my bad, I looked only at the curse and modrinth pages, and forgot about source control

**Review by TacoMonkey11 — APPROVED** [review]

**Pull request merged**
