### PR TITLE
New manifests

### PR DESCRIPTION
**Pull request by thefirethirteen**
A full changelog can be found at [https://github.com/thefirethirteen/modget-manifests/commits/master](url).

Add support for various mods and update the lookup table.
Also fix some pre-existing manifests.

### CODE REVIEW

**Review by NebelNidas — CHANGES_REQUESTED** [review]
Although generally, it is the right approach to only list Minecraft versions marked as compatible, this Sodium version does in fact work perfectly fine with the versions you removed (I've tested it myself and had it confirmed on the CaffeineMC's Discord server). So in this case, it is fine to list them ;)

**Comment by thefirethirteen** [comment]
> 
> 
>     * [979cd1d#diff-9952b6a5acfbf5830f66209b8e1b3cf388ce2816294e647156bcbb5568855859L19](https://github.com/ReviversMC/modget-manifests/commit/979cd1d75a2b15dd5a02040a301356b55b8dee3a#diff-9952b6a5acfbf5830f66209b8e1b3cf388ce2816294e647156bcbb5568855859L19):
>       Although generally, it is the right approach to only list Minecraft versions marked as compatible, this Sodium version does in fact work perfectly fine with the versions you removed (I've tested it myself and had it confirmed on the CaffeineMC's Discord server). So in this case, it is fine to list them ;)

Noted!

**Comment by NebelNidas** [comment]
Looks good! 👍 The only other thing I've noticed is that `fabric` in Fabric API's package name is lower-cased, while per spec it should be capitalized: https://github.com/ReviversMC/modget-manifests/blob/master/doc/manifest-spec-v2.md#yaml-specification

**Comment by thefirethirteen** [comment]
> 
> 
> Looks good! 👍 The only other thing I've noticed is that `fabric` in Fabric API's package name is lower-cased, while per spec it should be capitalized: https://github.com/ReviversMC/modget-manifests/blob/master/doc/manifest-spec-v2.md#yaml-specification

Fixed and noted!

**Comment by NebelNidas** [comment]
Manually looking through each or your submissions is quite a lot of work, that's why I'm currently working on a GitHub workflow which does this automatically for me. Once this is done, I'll let it check this PR and merge it if everything works fine!

**Comment by thefirethirteen** [comment]
Got it! I'll wait for that to be done for any other PRs.
Also, my commits can be a little chaotic. Sorry for that. :)

**Comment by thefirethirteen** [comment]
I think there are more fixes to be done, so I'm going to go review everything myself again.
Also, as the github bot is being worked on, I'm waiting for that too.

**Comment by NebelNidas** [comment]
Looks good all around! I will finally merge it now, sorry for having taken this long. 😅

**Comment by thefirethirteen** [comment]
Huh, I thought I left it as a draft.
With good reason, the manifests are outdated (some are, especially fabric).
I will sort this out asap.

**Comment by NebelNidas** [comment]
No problem, I just wanted to get the main repo more up to date ;-)

**Comment by thefirethirteen** [comment]
Ah, got it!

**Pull request merged**
